//USER
export const UPDATE_USER = 'UPDATE_USER';
export const RESET_USER = 'RESET_USER';

// DASHBOARD
export const SELECT_EVENT = 'SELECT_EVENT';
export const UPDATE_EVENT_DURATION = 'UPDATE_EVENT_DURATION';
export const TOGGLE_BOOKING_MODAL = 'TOGGLE_BOOKING_MODAL';
export const SET_IS_BEING_UPDATED = 'SET_IS_BEING_UPDATED';
export const SET_EVENT_VIEW = 'SET_EVENT_VIEW';
export const SET_CALENDAR_EVENTS = 'SET_CALENDAR_EVENTS';
export const SET_CALENDAR_TEAM_EVENTS = 'SET_CALENDAR_TEAM_EVENTS';
export const CLEAR_ALL_EVENTS = 'CLEAR_ALL_EVENTS';
export const SET_ERROR = 'SET_ERROR';

// EMPLOYEES
export const FETCHING_EMPLOYEES = 'FETCHING_EMPLOYEES';
export const FETCHING_EMPLOYEES_SUCCESS = 'FETCHING_EMPLOYEES_SUCCESS';
export const FETCHING_EMPLOYEES_FAILURE = 'FETCHING_EMPLOYEES_FAILURE';
export const UPDATE_SELECTED_EMPLOYEE = 'UPDATE_SELECTED_EMPLOYEE';

// TEAMS
export const FETCHING_TEAMS = 'FETCHING_TEAMS';
export const FETCHING_TEAMS_SUCCESS = 'FETCHING_TEAMS_SUCCESS';
export const FETCHING_TEAMS_FAILURE = 'FETCHING_TEAMS_FAILURE';
export const CREATING_NEW_TEAM = 'CREATING_NEW_TEAM';
export const CREATING_NEW_TEAM_SUCCESS = 'CREATING_NEW_TEAM_SUCCESS';
export const CREATING_NEW_TEAM_FAILURE = 'CREATING_NEW_TEAM_FAILURE';
export const UPDATE_SELECTED_TEAM = 'UPDATE_SELECTED_TEAM';

// CLIENTS
export const FETCHING_CLIENTS = 'FETCHING_CLIENTS';
export const FETCHING_CLIENTS_SUCCESS = 'FETCHING_CLIENTS_SUCCESS';
export const FETCHING_CLIENTS_FAILURE = 'FETCHING_CLIENTS_FAILURE';
export const CREATING_NEW_CLIENT = 'CREATING_NEW_CLIENT';
export const CREATING_NEW_CLIENT_SUCCESS = 'CREATING_NEW_CLIENT_SUCCESS';
export const CREATING_NEW_CLIENT_FAILURE = 'CREATING_NEW_CLIENT_FAILURE';
export const UPDATE_SELECTED_CLIENT = 'UPDATE_SELECTED_CLIENT';

// LOADING
export const SET_LOADING = 'SET_LOADING';
